
LOAD DATA LOCAL INFILE 'data/airports.csv' 
INTO TABLE airports 
FIELDS TERMINATED BY ',' 
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'data/passengers.csv' 
INTO TABLE passengers 
FIELDS TERMINATED BY ',' 
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'data/flights.csv' 
INTO TABLE flights 
FIELDS TERMINATED BY ',' 
IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'data/tickets.csv' 
INTO TABLE tickets 
FIELDS TERMINATED BY ',' 
IGNORE 1 LINES;
